### ISSUE TITLE
Kotlin mods cause crash...

### ISSUE THREAD

**Issue by Witherking25** [architectury/architectury-transformer#14]
```
[Architectury Transformer] Architectury Runtime 5.2.61
[Architectury Transformer] Read classpath in 1.211 s
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:340)
	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:321)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:234)
	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:762)
	at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1033)
	at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:883)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:848)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at dev.architectury.transformer.handler.TransformerClassWriter.get(TransformerClassWriter.java:54)
	at dev.architectury.transformer.handler.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:33)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.Frame.merge(Frame.java:1299)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.Frame.merge(Frame.java:1244)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at dev.architectury.transformer.handler.SimpleTransformerHandler.toByteArray(SimpleTransformerHandler.java:215)
	at dev.architectury.transformer.handler.SimpleTransformerHandler.applyTransforms(SimpleTransformerHandler.java:188)
	at dev.architectury.transformer.handler.SimpleTransformerHandler.lambda$handle$1(SimpleTransformerHandler.java:80)
	at dev.architectury.transformer.input.FileView.lambda$handle$1(FileView.java:47)
	at dev.architectury.transformer.input.BaseFileAccess.handle(BaseFileAccess.java:82)
	at dev.architectury.transformer.input.FileView.handle(FileView.java:45)
	at dev.architectury.transformer.input.ForwardingFileView.handle(ForwardingFileView.java:24)
	at dev.architectury.transformer.input.ForwardingFileView.handle(ForwardingFileView.java:24)
	at dev.architectury.transformer.handler.SimpleTransformerHandler.handle(SimpleTransformerHandler.java:78)
	at dev.architectury.transformer.Transform.runTransformers(Transform.java:104)
	at dev.architectury.transformer.Transform.runTransformers(Transform.java:98)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:165)
```

**Comment by shedaniel** [comment]
I believe this can be fixed by a `--refresh-dependencies` and has nothing to do with kotlin, unless otherwise.
